# Generated by Django 4.2.4 on 2023-08-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="user_rdp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id_add_by", models.CharField(max_length=10)),
                ("Ip_address", models.IntegerField()),
                ("Username", models.CharField(max_length=20)),
                ("Password", models.CharField(max_length=100)),
            ],
        ),
    ]
