# Generated by Django 4.2.4 on 2023-08-30 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_rdp",
            old_name="emp_id_add_by",
            new_name="Emp_Id",
        ),
        migrations.RenameField(
            model_name="user_rdp",
            old_name="Ip_address",
            new_name="IP_Address",
        ),
    ]
