# Generated by Django 4.2.4 on 2023-08-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0004_alter_user_rdp_ip_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_rdp",
            name="IP_Address",
            field=models.GenericIPAddressField(),
        ),
    ]
