# Generated by Django 4.2.4 on 2023-09-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0006_alter_user_rdp_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_rdp",
            name="Status",
            field=models.CharField(default="pending", max_length=100),
            preserve_default=False,
        ),
    ]
